name: Finance-Project CI/CD

on:
  push:
    paths:
      - "api/**"
    branches: ["main"]

env:
  FUNCTION_NAME: "Finance-Project"

defaults:
  run:
    working-directory: ./api  

permissions:
  id-token: write
  contents: read

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.x"

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o ./publish --no-build

      - name: Create Zip File
        run: |
          DATE=$(date +'%Y-%m-%d')
          cd ./publish
          zip -r "../function_$DATE.zip" ./*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::407215534303:role/GitHubActionAssumeRole
          aws-region: ap-southeast-2

      - name: Push to S3
        run: |
          DATE=$(date +'%Y-%m-%d')
          aws s3 cp "function_$DATE.zip" s3://your-finance-project-release-bucket

      - name: Update Lambda
        run: |
          DATE=$(date +'%Y-%m-%d')
          aws lambda update-function-code --function-name ${{ env.FUNCTION_NAME }} --s3-bucket your-finance-project-release-bucket --s3-key "function_$DATE.zip"
